---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: flawnrayen
    password: Rayen123456

- name: Tag and push to docker hub
  docker_image:
    name: devops
    repository: flawnrayen
    tag: latest
    source: local
    push: yes

