---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: flawnrayen
    password: Rayen123456

- name: Push the Docker image into the repo
  shell: docker login --username flawnrayen --password Rayen123456 
  shell: docker push flawnrayen/devops:latest
