---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: mohamedbenmiled
    password: Mohamed+23

- name: Push the Docker image into the repo
  shell: docker push mohamedbenmiled/devops:latest
